### ISSUE TITLE
api responds to malformed jwt header with 500

### ISSUE THREAD

**Issue by slugalisk** [MemeLabs/scala-api#1]
when creating a poll with a malformed jwt header (ie. for an unauthenticated session) the server returns an http code 500 with the response

```json
{"error": "The token was expected to have 3 parts, but got 1."}
```

expected: probably a 401 error?

**Comment by nom-d-plume** [comment]
https://github.com/MemeLabs/scala-api/commit/7a721cdcf85ef052dbc402446d17c89d05619eeb
